version: "1"
rules:
  - base: master
    upstream: solgenomics:master
    mergeMethod: merge
    assignees:
      - nickpalladino
      - mlm483
      - dmeidlin
      - davedrp
label: "upstream-merge"
